### ISSUE TITLE
Versions 1.14 and 1.15 unavailable on JetBrains plugin site

### ISSUE THREAD

**Issue by mkillianey** [davidsommer/IconViewer#11]
Could you advise as to how you'd prefer end-users (who don't want to build from scratch) to get changes from 1.14 and 1.15?

As of Oct 19, 2019, the latest version available at https://plugins.jetbrains.com/plugin/9710-iconviewer/versions seems to be 1.13, published back in 2017.  Is there an expectation that 1.14 and/or 1.15 will be published there, or is this project spinning down, and you'd recommend one of the forks, like perhaps:
https://github.com/mallowigi/Image-Icon-Viewer
Which is being published as:
 https://plugins.jetbrains.com/plugin/11096-image-icon-viewer/versions

**Comment by davidsommer** [comment]
I would go to https://github.com/mallowigi/Image-Icon-Viewer. Since i'm not getting enough time to invest in this privat project.
