### ISSUE TITLE
AS 3.1 is unable to display

### ISSUE THREAD

**Issue by Thewhitelight** [davidsommer/IconViewer#6]
![image](https://user-images.githubusercontent.com/7720611/38072414-b10d574c-3358-11e8-8862-d90fd2f4d156.png)

**Comment by davidsommer** [comment]
@Thewhitelight  i have no idea what kind of picture format AS 3.1 is... can you post the file here?

**Comment by Thewhitelight** [comment]
![bg_arrow_right](https://user-images.githubusercontent.com/7720611/38283695-0fa80262-37ea-11e8-926b-af65a2f94d14.png) like this

**Comment by LiLinXiang** [comment]
@davidsommer I clone this project and rebuild it, import my Android Studio 3.1 ，he has back to normal and can use, by I don`t know why...
