### ISSUE TITLE
Android Studio 3.1 unable to display And Fix it

### ISSUE THREAD

**Issue by LiLinXiang** [davidsommer/IconViewer#8]
I clone this project and rebuild it, import my Android Studio 3.1 ，he has back to normal and can use, by I don`t know why...

**Comment by LiLinXiang** [comment]
`image = ImageLoader.loadFromStream(new BufferedInputStream(new FileInputStream(containingFile.getVirtualFile().getCanonicalFile().getCanonicalPath())));`

`image = Toolkit.getDefaultToolkit().getImage(containingFile.getVirtualFile().getCanonicalFile().getCanonicalPath());`

replace it，it will be ok

**Comment by davidsommer** [comment]
should be working now, thx
